### ISSUE TITLE
Display map option from seeded AB maps

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#184]
When you open up the menu an option called ''Display map'' would appear.

This basically recreates the map as it would generate in AB, so that you do not have to join it to check it out. Could also help in trades.

QoL addition

**Comment by MXKhronos** [comment]
This is pretty tricky to do since the map is dynamically generated when you enter AB, so the layout can't exactly be loaded outsided AB unless I save the data of the seed's layout to Roblox and then have to pull it from Roblox when you want to view the layout. 
But I think this QoL would be important and I'll try to work on it when I have the time.
