### ISSUE TITLE
Abandoned bunkers seeded maps

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#186]
Abandoned bunker loads a random seed if a player without the map enters it.

However a if a player that is currently holding a seeded map enterS the lobby it will instead CHECK which player joined first and pick that map seed if that player is holding any. Otherwise, it will be random.

This is especially noticable if you try to invite other people to a specific map seed you're holding or trying to invite people to. People usually enter the map and join the lobby before the host can do, which results in a random map seed.

**Comment by MXKhronos** [comment]
Due to the way being on game lobby menu is seperate from how the player got to the lobby menu. In order to get into the lobby with the right seed, the host will have to be the one joining first. I added a couple things to help with that.
- Added host icon to lobby screen that shows the host player.
- Lobby screen now shows the active seed the lobby is using.

For now, if you have a map with the seed you want, you can enter abandoned bunker raid via the doors in residentials while having the map equipped and create/join an empty lobby. That way, you are the host to begin with. Otherwise you'll have to create a new lobby after interacting with the map last.

**Comment by MXKhronos** [comment]
Closing this until I can think of further improvements.
