### ISSUE TITLE
Armor and health point mods aren't in any droptables

### ISSUE THREAD

**Issue by MrPigZ** [HelixNebulaStudio/RiseOfTheDead#195]

**Comment by MXKhronos** [comment]
This is intended, and will occur to other mods in the future where they may get shuffle in and out of drop tables.

**Comment by Leroy8888** [comment]
I don't think it's a good idea to limit mods in their droptables. We have content, but it's not that much yet. The mods we currently have for example aren't enough to fully fill in a torso armor clothing piece. It would really just lower the diversity players can use on their armor.

It would work if we had more mods to boot them up, but as it currently stands them being a replacement for the mods we had prior is severely limiting. As I can see, the main point of the new mods is that they provide more points then the armor and health chestpiece mods, but they require something to be done in order to achieve that. If the player wouldn't like to either hold out a consumable or kill targets to get a health buff an armor or health mod would likely just do fine.

**Comment by MXKhronos** [comment]
Hmm, you're right. I've re-added them to drop tables.
