### ISSUE TITLE
Faction mission complete time

### ISSUE THREAD

**Issue by MemenTheMeme** [HelixNebulaStudio/RiseOfTheDead#235]
Accepted food airdrop mission [in railway] and immediately traveled to train station with gps and entered raid. Mission expired before Icould complete the raid, despite taking less than 20 seconds from the time I started the mission to the time I got into the raid

Also had a horde clear mission where I immediately traveled to Sundays and only had 5 minutes to get 300 kills.

Not sure if these are intentional times, but the timer for the missions should be increased so people actually have time to complete them.

**Comment by Rookie21333** [comment]
yeah some of them are hard since in railways there are zombies getting stuck and love to waste our precious time and there are also times that i need to kill few more zombies but there arent zombies there. then i was so CLOSE of getting that supply and the mission expired and failed the mission and some of our faction member failed that mission too.

**Comment by GregTheBestest** [comment]
You can actually go to the raid and accept faction mission at the really end I believe.

**Comment by Rookie21333** [comment]
> You can actually go to the raid and accept faction mission at the really end I believe.

you can do that but the raid is randomized and may not be railways than you can expect

**Comment by GregTheBestest** [comment]
Ah yes, how I could have forgotten it. Yet if you have other people you can know which raid it will be as it is same for everybody
