### ISSUE TITLE
Fumes

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#258]
Fumes create a heavy cloud of hazardous fumes, obscuring himself and his location. You can randomly spray into his cloud and hope to kill him or you can enter his cloud to find and kill him..

- When you are within 100 units of Fumes. Fumes will spawn a Fumes Cloud.
- Fumes Cloud does 6(Hard: 30) health damage per 0.5s.
- If you have gas protection equipped, the damage is reduced by gas protection%. `labcoat` grants an additional 30% protection.
- While you're in the cloud, your gas protection clothing will take damage one by one, once broken they will no longer protect you from the damage.
- You can repair your gas protection clothing in the shop with money.
- Fumes will hide inside the Fumes Cloud unless player is too far away.
- In easy mode, Fumes will not move around in the Fumes Cloud, in hard mode he will move around.
- Fumes is not detectable by threatsense and does not have weak points.

**Comment by Leroy8888** [comment]
The` labcoat` currently doesn't have any gas protection yet.

When clothing pieces break with gas protection it won't degrade other clothing with that stat and there also seems to be a priority to what it targets as it destroys `divinggoggles` over a `hazmathood`.

The damage reduction is based of the clothing piece that is currently being damaged, even if a piece with better gas protection is equiped.

The gas protection doesn't stack which might be intentional, however it doesn't reduce the gas damage by the highest gas protection clothing piece if multiple pieces with that stat are equiped.

**Comment by Leroy8888** [comment]
@MXKhronos Sorry for the mention, but since the release date was set to tomorrow and these issues still seem to persist I figured a short reminder might be helpful.
