### ISSUE TITLE
Consider having local spawn caps for each area or a minimum amount of zombies for each area

### ISSUE THREAD

**Issue by zxcvbgfrtyui** [HelixNebulaStudio/RiseOfTheDead#302]
After killing zombies in certain areas, it seems that the replacement zombies don't always spawn in the same area. This can cause the number of zombies in an area to drop significantly if few zombies are being killed in other areas, which makes farming continuously in those areas inefficient with weapons that can damage many targets and in extreme cases, seems to cause an area to have no zombies for a moment, even with only a single player farming the area.

![Roblox 20_05_2024 11_03_01 PM](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/edb478da-80ce-4863-b8c9-eb7af6aa4dd0)
This was taken about 10 seconds after I stopped killing zombies, so maybe I didn't wait long enough, but the number of zombies in front of Bloxmart (not in front of the warehouse) can be counted with one hand.

![Roblox 20_05_2024 11_09_44 PM](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/169975582/3b7b35c0-e388-4c41-b55c-f17e771dc0a7)
I took this photo after going inside of the warehouse, doing some stuff and coming back out. While less severe, the number of zombies in front of Bloxmart is far below what I've seen previously.

**Comment by Leroy8888** [comment]
Hmm, odd. I've been farming with a few other accounts as well and did test if the adjusted spawns would severely impact the leveling grind. When I did so however I didn't really experience a steep decrease in zombies available to farm.

This issue was present when the update launched as it seems to have gone through a few changes. It seemed to be doable again 2 weeks after the update launched.

A thing to note, I do believe zombies can get stuck on objects be it in or out of bounds. They aren't considered dead, so those which are stuck won't spawn or teleport back to the area they spawned in taking away available spots and making certain areas look empty. This is especially present if a player uses a weapon with knockback to mess with the positions of zombies.

Something to note however is that compared to prior versions zombies now spawn in one by one where in older versions zombies would instantly spawn in groups of 5 - 15 depending on the amount of zombies killed.

**Comment by zxcvbgfrtyui** [comment]
Probably should mention that my reasoning for zombies spawning in other places is that I farmed the Bloxmart area only and watched the amount of zombies in the warehouse area go up to 8 I think, double the amount pre-update

**Comment by MXKhronos** [comment]
By any chance the zombies walked towards Sundays during a horde attack event?

**Comment by zxcvbgfrtyui** [comment]
It is possible that they had walked towards Sundays previously, but, during Horde Attacks, I was killing the zombies before they exited the garage door. If it was due to previous Horde Attacks, there had to be both:

- no/few zombies being killed at Sundays (which would cause them to respawn at the Bloxmart area)
- most of the zombies getting stuck or continuously attracted to a scarecrow/snowman/player somewhere on their way back (which would prevent them from returning to the Bloxmart area)

I find it difficult to believe that both of these would occur, especially for half an hour, because the server was about half-full with multiple players moving through the area in front of Bloxmart and I have previously (not this time as I was in the Bloxmart area) often witnessed zombies successfully returning without becoming stuck. However, there is a possibility that a scarecrow/snowman/player was positioned along the return path, out of reach of the zombies, which would explain the second point.

Additionally, as I mentioned earlier, the spawn limit seems to be global, not local, because as I killed the zombies in the Bloxmart area, the number of zombies in the warehouse area rose to at least double the amount pre-2.0. A global spawn limit would reduce the number of zombies in places where zombies were being killed more frequently than other areas.
