### ISSUE TITLE
Medical Breakthrough

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#48]
New side mission, Medical Breakthrough. Rachel has an epiphany about Stan and the possibility of his blood.

New mission items, Blood Sample, Sample Report.

Unlocks board mission, Ziphoning Serum.

I removed the countdown sequence, it's now a dialogue timer. When the timer runs out, the patrol bandit will become hostile.

**Comment by JakobCh** [comment]
Is it intentional that you have to hold the jerrycan to fuel the generator? Don't remember that being the case in the other quests/locations that use generators like that.

**Comment by JakobCh** [comment]
Some of the bandits seem to have a lot of health for being level 3, think I hit one with a 20k+ damage rocket without them dying.

**Comment by MXKhronos** [comment]
> Is it intentional that you have to hold the jerrycan to fuel the generator? Don't remember that being the case in the other quests/locations that use generators like that.

Yes, it's intentional, other cases with fueling the generator will also be updated eventually.


> Some of the bandits seem to have a lot of health for being level 3, think I hit one with a 20k+ damage rocket without them dying.

The bandits are using the armor mechanic that similar to the players. Breaking the first armor can absorb all the damage.

**Comment by JakobCh** [comment]
> The bandits are using the armor mechanic that similar to the players. Breaking the first armor can absorb all the damage.
Ah alright, I was spawning in Level 3 bandits with commands to compare too but I guess those don't have armor by default.

**Comment by Leroy8888** [comment]
I've found quite a few issues last session I tested this mission. I'll state them all here and will try my best to describe them;

- You can use an empty jerrycan to fuel the generator

- Structures can be placed during the mission, which can block off the path for the negotiating bandit. You can also slow down the negotiating bandit with ranged (rifles) or melee knockback. The bandit does not seem to retialiate when you do this.

- You can kill the negotiating bandit before it enters its offensive mode. This can either be replicated by shooting the bandit when it walk up to the scanner area with a incendiary weapon or shoot it during the conversation part when if you already have a weapon drawn out.

- The negotiating bandit keeps talking while it is dead, such as using the lines to indicate the player should hurry up. The bandit will also instantly attack the player after the dialogue ends such as after bribes or after telling that you were send by Zark, instead of walking away and calling in reinforcements.

- Bandit reinforcements won't spawn unless the negotiator is killed. This also opens up the possibility to avoid all combat by constantly looping the bandit when it starts attacking. Since it does not temper with the scanner in any way.

- Blood samples not degrading upon taking damage and it seems to occur randomly, but I am not exactly sure what causes it.

- If you fail the mission the game will attempt the player to world ''nil''. This doesn't do anything and the player will respawn after being killed in the same world.

- The player can collect multiple samples after failing the mission, which is linked to not being able to progress the mission after failing it.

- The player can bribe with the bandit for money despite not having enough money and this will end up putting the player's money value in the negatives.
