### ISSUE TITLE
Marked-for-closure tag

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#531]
What is the purpose of this tag? Was this manually introduced or is this an automated procress by Github?

There are a few issues which have not been patched but are closed as is due to them reaching the tag time limit.

**Comment by MXKhronos** [comment]
It's automated, it's sorta a reminder to revisit an issue and if it's important then a bump comment would reset the timer. Otherwise it's just there to clean up old issues that are either fixed but not marked as complete, an old question issue, etc.. It takes 2 month before an issue is marked for closure, and another 7 days before it's closed.
