### ISSUE TITLE
Is Dr. Sinister supposed to chase and attack players when no zombies are present?

### ISSUE THREAD

**Issue by zkkuu** [HelixNebulaStudio/RiseOfTheDead#533]

**Comment by zxcvbgfrtyui** [comment]
That would be my guess. It would make sense since Dr Sinister would otherwise be useless after all of the offensive zombies are killed. Not sure why Dr Sinister refuses to attack when the player comes close to it while offensive zombies are around though, since it would effectively be free damage. I'd suggest making Dr Sinister attack players that get too close, but not necessarily pursue players while offensive zombies are around.

**Comment by MXKhronos** [comment]
Yes, Dr. Sinister can attack players if no zombies are near. And attacking players if they are near should be a thing too even when zombies are near.

**Comment by zxcvbgfrtyui** [comment]
It's possible that I've avoided getting hit by Dr Sinister due to having a melee out, but I think that I've spent a decent amount of time constantly near Dr Sinister (leading nearby zombies away before returning and meleeing Dr Sinister for multiple seconds) and I've never been hit by Dr Sinister while other zombies were nearby.

**Comment by MXKhronos** [comment]
> It's possible that I've avoided getting hit by Dr Sinister due to having a melee out, but I think that I've spent a decent amount of time constantly near Dr Sinister (leading nearby zombies away before returning and meleeing Dr Sinister for multiple seconds) and I've never been hit by Dr Sinister while other zombies were nearby.

Oh my bad, let me clarify, they currently do not attack when they are near zombies, but I think they should be able to.

**Comment by zkkuu** [comment]
> > It's possible that I've avoided getting hit by Dr Sinister due to having a melee out, but I think that I've spent a decent amount of time constantly near Dr Sinister (leading nearby zombies away before returning and meleeing Dr Sinister for multiple seconds) and I've never been hit by Dr Sinister while other zombies were nearby.
> 
> Oh my bad, let me clarify, they currently do not attack when they are near zombies, but I think they should be able to.

Tested Dr. Sinister in Dev Branch, he doesn't attack me at all, both when he's alone and when there are zombies. He just chases me around like a normal zombie but does not attack me, and if there are zombies, only they attack me but not him.

![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/5151ec6b-6af6-44cb-92c7-2acc05f27439)
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/209e4331-aec5-41bf-a36e-f01684ce26d6)
(Off-topic, but can you update the NPC asset pack with their new clothing and add all the zombie variants, Dr. Sinister, both pre-2.0 and current, and Pathoroth's true form in the Enemies asset pack for the wiki?)

**Comment by zxcvbgfrtyui** [comment]
Back when I played (pre-2.0), Dr Sinister did attack me when it was alone in Abandoned Bunker. It may have been broken by the 2.0 update or later.
