### ISSUE TITLE
Residential Community Members missing in W.D. Residentials

### ISSUE THREAD

**Issue by zkkuu** [HelixNebulaStudio/RiseOfTheDead#541]
Dallas, Kelly, and Zep are all absent and do not appear in the Community Safehouse except for Nate, who's glitching near the workbench.

**Comment by Leroy8888** [comment]
it seems like some script is failing. In Nate case it seems like he's trying to lock on to a enemy. It should be noted that there have been some reports where Nate attacks Joseph or at least, tries to.

Log: 
![Schermopname (13012)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/6001ea25-68f9-4c1e-bcc6-4da81c7742bf)

**Comment by Leroy8888** [comment]
Update, this seems to be caused by Robert. All NPCs for some reason attack him. This issue also causes regular zombies to despawn if they agro onto a player, but this only occurs if Nate loops in his respawning state. 

When the mission `Something's Not Right` is active and robert is at the safehome, Nate will start shooting at him. Robert is client sided, so for most players Nate will be shooting at nothing.

This issue is related to #543

**Comment by zxcvbgfrtyui** [comment]
Nate also fires at Icarus, not just Joseph.
