### ISSUE TITLE
Corrosive's puddles cannot kill the player

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#545]
The puddles put the players health at 0 or -1, but they won't die to it. His melee attack still properly kills a player.

Players cannot equip or use anything in this state and only interact with prompts. Entities won't agro onto the player in this state.

**Comment by ShatteredVoidCrystal** [comment]
this happened to me before (it happened to you i think?), I thought it was because of warmonger's scales, but it seems its just the puddle itself, and I did try fast travelling to another subplace but it automatically healed me or just reset me since i was 0 hp. If people mess around enough with this, they could most likely bug the game out.
