### ISSUE TITLE
Trying to take a weapon part out of either the primary or secondary groups breaks a couple things

### ISSUE THREAD

**Issue by MrGarrettFerret** [HelixNebulaStudio/RiseOfTheDead#570]
When trying to do the aforementioned the part's texture does not show on the workbench unless edited again, and the part appears separately from the group (see image). 

![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162447919/761ba6f3-16d6-484a-8996-4525716f9ee2)

**Comment by Leroy8888** [comment]
I believe it's possible to add parts seperately from groups, but lone parts do take priority. Should you include it in a group it would default to the config of the lone part. Removing `Handle` from the modified menu would cause it to copy their appearance configs and apply it to said part if it is present in a group.

It's like some sort of ''save'' and removing a part from a group deleted that ''save''. It also does kind of suck that in order to remove a layer or circumvent some priorities you would have to reset or ''delete'' a modified part (group) which has customization data on it.

**Comment by MXKhronos** [comment]
Should be fixed now.
