### ISSUE TITLE
Workbench Customization Menu Test

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#599]
### Discussed in https://github.com/HelixNebulaStudio/RiseOfTheDead/discussions/523

<div type='discussions-op-text'>

<sup>Originally posted by **MXKhronos** June 18, 2024</sup>
Removal of default rust materials of low condition weapons.

With the new Appearance Menu rework, item conditions will unlock different tiers of customizations of your item.
</div>

### Final test for any major issues
Copy & Paste is finished, fixed a few other bugs with deleting layers. Fixed breakdown formatting. 

Notes:
- Copy and paste does not copy Part Scale and Offsets because those are independent per part.
- Previously animated patterns (e.g. Ghost RGB, Wind Trails, ...) will not be available in the Pattern selection. It will be moved out to the Skin-Permanent section and show up if you have the skin pack unlocked. This is due to animated textures using a seperate layer and are not customizable.
- Saving mechanics will be polished, currently it saves when you:
    - Switch tabs on the workbench (Build, Process, Upgrades, etc..)
    - Change a configuration which isn't a slider
    - Closes workbench
- Frostivus Skin-Perm will be altered due to incompatibility, the new design hopefully won't be too different.

**Comment by Leroy8888** [comment]
skin permanents like frostivus don't seem to have the ability to adjust the transparency of the permanents. It would be nice to have that, since it also played a part in how weapon conditions worked prior to the rework (battle tested > transparent / factory new > fully visible).

It also appears the windtrails skinpack does not have a animated skin anymore, compared to cotton fade or Cute skulls for example. Maybe one can be added as permanent skin as well?

**Comment by Leroy8888** [comment]
I also noticed that it's live in main branch, but only via the /optin command. Why was it not fully integrated yet? It doesn't seem like the place to test it and it could potentially endanger the data of some users or cause other issues if it turns out that there unintended features to it.

We just had (yesterday) a patch for the skins not properly saving, along with a few changes to convert old appearances, dubbed as ''best-effort''. It seems too early to really tell whether this would be perfectly functional.

Just curious to why it was launched the way it currently is.

**Comment by MXKhronos** [comment]
It's only via /optin because it's a feature for opting-in for now and it'll be opt-in for a long while until people got familiar with it and iron out some edge case issues then the old system will be entirely replaced.

Yeah, the saving issue may be another case, and I'm still diagnosing it, I should've clarified, by "best-effort", it means what can be converted over to the new data will be converted. Some old appearances will be lost e.g. Spooky Skeleton Rgb data type is different from the skin perm Spooky Skeleton. Other things that may not be converted can be due to some part name changes, and other unforeseen incompatibilities. 

It's done this way for a wider testing for anyone who are okay with opting-in the new system with a slight risk. It's stated when you use the `/optin NewCustomizationMenu` command.

**Comment by Leroy8888** [comment]
The layers from the skin permanents section seem to appear in the ''Colors'' section of the customization menu. With this, you cannot apply a color as otherwise the permanent pattern will be overwritten by the color, wiping it from the weapon.

it also seems like there's some inconsistancy with these parts of the perm skin in the ''Patterns'' section. I've unlocked the halloween pixelart and CuteButScary texture for it, but I can only seem to use them as permanent skins. They seem to be (partly) locked and I am not quite sure why. They also do not cycle through colors, but instead remain the same color, unlike when the player directly selects it as a permanent skin.
![Schermopname (13219)](https://github.com/user-attachments/assets/9b5ee447-141d-4320-a14d-4fcce32d0b39)

Also to note, the permanent skins cannot be combined with textures or colors, it's either the perm pattern or texture for most instances. It would be really nice to add a seperate adjuster for perm skin transparency.

**Comment by MXKhronos** [comment]
Due to how texture animations are applied, skin perms will only have texture animations. They will come with a raw texture for the custom texture section if the weapon has the skin perm unlocked.

There is a bug where the background of these skin perms aren't colorable without it replacing the skin, which will be fixed.
