### ISSUE TITLE
Customizing a Weapon resets the entire Weapon Appearance

### ISSUE THREAD

**Issue by zkkuu** [HelixNebulaStudio/RiseOfTheDead#607]
When attempting to color a weapon part, it will, for some reason, reset the entire weapon's appearance. This only works if it is an individual part and not the "All",  "Primary",  or "Secondary" options. Much like https://github.com/HelixNebulaStudio/RiseOfTheDead/issues/589 (Which can still happen randomly by the way), it's really a nuisance when someone has spent a lot of time customizing something only for it to vanish and has to start all over again.

Here's the developer console when this happened in a 2-hour old public server.

![image](https://github.com/user-attachments/assets/a8e75f8e-858e-4d86-972e-98c08c9cb99c)

**Comment by Leroy8888** [comment]
it seems like this issues occurs because of how the weapons recover their appearance prior to being opted in.

The weapons only retrieve their appearance when the menu in the workbench is opened, if you do not open the menu, opt in and then draw out a weapon they will all contain their default look.
