### ISSUE TITLE
Belly of the Beast

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#63]
A side mission to obtain the Portable Auto Turret.

---

1. Once the mission is available. You will find a **Turret Blueprint Piece** when opening **SunkenShip Chests**.
2. You can then ask the Mysterious Engineer about it to start the mission.
3. Mysterious Engineer tells you the other blueprint pieces were eaten by Elder Vexeron, so if you really really want the PAT, you are journeying into the beast.
4. By holding out a Vexling, you will be eaten and transported to the guts of Elder Vexeron.
5. There will be 2 Eaten Sunken Chests inside. One near the Head and one near the tail.
6. Once you got the 2 pieces, you can exit through the tail.
7. Mysterious Engineer then suggest the last piece may be somewhere near the Harbor seabed.
8. You’ll get the Sunken Salvages board mission added and upon doing the mission, you will see another Eaten Sunken Chest with the final piece.
9. Talking to the Mysterious Engineer will reward you with the PAT blueprint.

---

There's a low fidelity version of Elder Vexeron's insides for specific players, generally based on account information like whether or not they have premium, account age and etc..

**Comment by MrPigZ** [comment]
Issues:
Players trying to do this mission will be confused because mission's first objective is to talk to the engineer and he has no quest dialogue. I don't know how player is supposed to know that he needs to get a blueprint part from sunkenship chest in order to actually start the quest. Players will either think this mission is bugged or go search information about it outside of the game.

A lot of people have claimed that they have died "randomly" or from "nothing" in sunken ship co-op when in reality they died from drowning. Inside of vexeron you take damage and nothing is indicating but the hp bar. Armor doesn't get broken, directional damage indicator doesn't show up and there are no "attack sounds". 🤔 Maybe we also need something to indicate that player is drowning like colours fading away and vision getting dark.

Bug:
The mission objective doesn't update when player has picked up both blueprint parts.
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162422862/b6275bbb-fd8f-46f2-aea2-f4e8292f020b)
