### ISSUE TITLE
moving items around in premium inventory or moving items INTO premium inventory resets the positon of the item and some kind of roblox popup appears

### ISSUE THREAD

**Issue by OpaquePillar** [HelixNebulaStudio/RiseOfTheDead#640]
https://github.com/user-attachments/assets/b8914915-9679-453b-af58-909ff8b84e16

i have no idea if the video works but issue is in title yeah
the popup says "Error: You already own this item. Your account has not been charged."

anyway yeah i cant move items into my prem inventory anymore and once i move them out i cant move them back in

**Comment by OpaquePillar** [comment]
ISSUE RESOLVED ITSELF for some reason like half an hour after i posted this so thats cool i guess

**Comment by Leroy8888** [comment]
This might happen in safehome due to some issue at safehome with loading data. This issue wouldn't be the only exception to this. A very common example would be clothing not loading, but has also proved to influence missions, weapon tweaks and a few more correlated issues.

These revert back to their original state after joining another world again.
