### ISSUE TITLE
Using melee weapon makes everyting bugged

### ISSUE THREAD

**Issue by Emiraga36446** [HelixNebulaStudio/RiseOfTheDead#699]
So lets say that i had a axe and when i use the axe and unequip it and do m1 İt does the axe animation later on when i equip anything from melee to maps to bombs to guns they dont work anymore they also lose their animations and stick to characters hand  which is the worst bug ever

**Comment by Leroy8888** [comment]
This effect only occurs when unequiping the fire axe. The tool functions like normal until then. When it is unequiped it breaks something which causes the player to be stuck in a state where they cannot use any handheld items.

This can only be fixed by reseting or leaving the server.

Log: 
![Schermopname (14065)](https://github.com/user-attachments/assets/095a0ef7-c629-4614-b870-bdbf29dc7a9d)
