### ISSUE TITLE
Slaughterfest and Cauldron Testing

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#734]
Want to release the first part of the update for Halloween. The only new reward at the moment is `jackolanternhaunted`, but more will be added soon. Halloween event will stay active throughout October to November from now on.

Just need to check if there's any edge cases causing issues. New things to test:

1. Slaughterfest top 3 rewards. **1st** gets 3 `slaughterfestcandybag`, **2nd** gets 2, **3rd** gets 1.
2. **Candy Hoarder**, mission id `82`. Complete Slaughterfest round with at least 500 candies.
3. **Mass Slaughterer**, mission id `83`. Complete Slaughterfest after getting 10 kills (doesn't reset).
4. Slaughterfest Cauldron: Tricks, exchanging candies with NPCs
5. Slaughterfest Cauldron: Treats, figuring out which NPCs to talk to (Only survivors) to get treats.
6. Slaughterfest Cauldron: Cook Antiques `slaughterfestcauldron` where you can have a reroll to obtain past Slaughterfest rewards.
7. Slaughterfest Cauldron: Cook Uncovered `slaughterfestcandyrecipes24` where you can cook rewards from this year's event. Recipes changes every 24 hours. (More new rewards will be added over time)

If there's anything I overlooked, please let me know! Thank you~

**Comment by MrGarrettFerret** [comment]
Did some solo testing for a bit. Found a some things:
- Candy Hoarder mission does not complete if you meet the requirements.
- If you're holding a gun while the round resets, the gui from the gun will be stuck on your screen (ammo count, crosshair) until you pick up another one.
- It seems the Ninja Fleet passive is enabled by default in the Slaughterfest, including the dash and the auto sprint. Is this intentional?
- You are able to exchange candies with an NPC an unlimited amount of times, is this intentional?
- It seems candy bags aren't given out in the Slaughterfest, neither from meeting the candy threshold nor from placement. (I was the only person in the server if that has anything to do with it)

Some suggestions:
- Maybe add an indicator to both the Trick and Treat sections of the cauldron to tell which NPCs you've already interacted with?
- Perhaps the required candies for the Haunted skin could shuffle each time you cook one.

**Comment by MXKhronos** [comment]
> It seems the Ninja Fleet passive is enabled by default in the Slaughterfest, including the dash and the auto sprint. Is this intentional?

Yes, I'll be taking feedback from gameplay with the new movement additions in order to ready it for Nekron's Gambit.

> You are able to exchange candies with an NPC an unlimited amount of times, is this intentional?

Yes, they refresh every day. 

> It seems candy bags aren't given out in the Slaughterfest

Yeah, it requires at least a kill for the placement to drop candybags. Board missions won't require so.

> Maybe add an indicator to both the Trick and Treat sections of the cauldron to tell which NPCs you've already interacted with

Npcs that already gave you treats will now be revealed in your Cauldron menu.

**Comment by MrPigZ** [comment]
Seems like Mike's hint "scar" is somewhat bugged. Mike still gave the candy when I spoke to him. He wasn't revealed in cauldron menu. 
![image](https://github.com/user-attachments/assets/7cf0f99c-ecde-4d16-8d54-00af35ea7f30)

**Comment by Leroy8888** [comment]
Would it be possible to reduce the cooldown of the Treats section of the cauldron to 10 mins in dev branch or give a command to instantly refresh them to quickly cycle through them and check them?

**Comment by MrPigZ** [comment]
In slaughterfest some times the round ends without announcing the top 3 players and rewarding said players.
Sometimes the round ends twice resulting in double rewards for the top 3.
Not enough time to figure out cause.

**Comment by Leroy8888** [comment]
You're still able to hurt yourself using the Fall Over emote via /ui Emotes. And it can be used to score kill(s) for the quests and candybag requirement.

When we tested a few rounds in SF we noticed that sometimes when a round ended it would just skip over the end part where it shows the leaderboard and how much candies everyone collected. It also skips the rewards and instantly restarts the round. It seems to be random, but It may be influenced by other players joining in.

PigZ was having an issue where he was unable to kill a wraith in SF but we're unsure what exactly caused it.

When rounds end in SF it also seems like the game check if you had enough candy to complete the candy hoarder mission, despite if it's active or not.

You can also reset your character in SF. This does not cause you to drop any candies, same if a wraith were to kill the player. Players will only drop candies if other players have at least hit them once. It can be abused to avoid losing candy if the player responds quick enough to other players. However, if a player respawns and gets hit without taking damage via the respawn shield and then reset is still contributes to the kill feed and the player would end up losing candies. 

The PaT can be used to kill wraiths. If it is mounted with an explosive weapon or projectile weapon it is able to kill players too if they're in range of wraiths. It's especially severe with Explosive weapons and flamethrower projectiles.

Cultist hood can still spawn cultists when hit by wraiths. They cannot hurt players however.

**Comment by Leroy8888** [comment]
I've cycled through a quite some treat seeds of the cauldron. They all seem fine.

Though I will admit that some of them can be a bit confusing. For example the ones that refer to hair color or formations. They usually end on ''Short Spikey Black'' or just ''Short Brown''. They seem like they're unfinished sentences when they're shown as ''Guy with Short Black''

**Comment by Leroy8888** [comment]
It seems that joining SF has a small chance to give the player an absurd amount of candy for the time that has passed. I've seen quite some people join SF on the last 20 seconds with around 800 candies, enough at times to secure a spot on the first 3 places. 

It does seem a bit unfair, could this be for example be halved if players join into a new match? It doesn't always seem to work, I've also seem people join in later rounds with 0 candies.

**Comment by MrPigZ** [comment]
Question regarding the SF missions. [Commit](https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/69d475d812cf818da5186e7398dd3923d1820139#diff-406b55e7cd6529151799c91d7c77ba2c7c25b8867a2538294487e471fd461baaR4) states that the missions would be "seperated" but the event missions are taking up the mission space. You cant have 6 normal missions and the event missions simultaneously. So is there a bug or am I interpreting the commit wrongly?

**Comment by MXKhronos** [comment]
> Question regarding the SF missions. [Commit](https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/69d475d812cf818da5186e7398dd3923d1820139#diff-406b55e7cd6529151799c91d7c77ba2c7c25b8867a2538294487e471fd461baaR4) states that the missions would be "separate" but the event missions are taking up the mission space. You cant have 6 normal missions and the event missions simultaneously. So is there a bug or am I interpreting the commit wrongly?

They shouldn't be added up, fixed it.

**Comment by MXKhronos** [comment]
@Leroy8888 @MrPigZ @MrGarrettFerret 

Quick feedback on the addition, hope to it release soon.

- Added new achievement, `slaughterfest2024`. Unlocked by cooking candies from the cauldron, you have 3 different recipes to choose from. You can level up this badge by cooking multiple times.
    - Added Slaughterfest 2024 leaderboard to shop.
- Moved Warehouse Safehouse Slaughterfest Cauldron to Sundays in order to make sure new players experience the main game first. 
- Removed Slaughterfest quick join from main menu. It misdirected new players to the event game mode, leading to player loss.

**Comment by Leroy8888** [comment]
I do like the that the cauldron moved from warehouse to sundays, redirect in the menu. Perhaps also some warning / notification above the rotating images of the ''Play Slaughterfest'' to indicate it is a PvP mode? Not really stated elsewhere besides in update logs or the `Mass Slaughter` quest. The ''Find'', ''Kill'' and ''Collect'' images actually make it seem like it's some sort of PvE mode, since a Wraith is used in the example. That would be at least to a new player. Most experienced players would know it's a PvP orientated event.

The levels for the badge seem a bit odd. I personally don't see a reason to level it other then to unlock it. It's a great way to shed some of the candy drops from the event, but that seems about it.

I feel like I am repeating myself quite often with this but I don't really see another implementation atm without brainstorming first. A reward besides the badge for a certain pass level milestone?

It could also be made in a way that doing certain things adds score to obtaining the badge. At milestones you would unlock the badge. You would also be able to continue to leaderboard spot. It still wouldn't really add a reason to continue grinding, but does add levels passively, much like how it did in the prior events while grinding for the rewards. Not exactly like MPbooks though, more or less, kill wraiths for example, kill different players (so not the same for the sake of alts), win SF rounds and more.

I also wanted to talk about the antique section cooldown to the topic. 5 hours for one reroll seems like a lot and you can gain a LOT more candies in the meantime. This way actually makes it more efficient to use throwaway alts to cycle through them. I think it would be better if another system was used to reroll the pool, like candies or some sort of ticket you could be obtained from doing activities. Maybe even from some PvE activities like hunting wraiths? A specific world event to boot where you can only kill them with a scythe to ''reap'' the tickets.

I am putting a lot on the table here, but introducing a competative PvP event seems rather difficult compared to the usual PvE events. Some of these could be kept in consideration for the next halloween event considering how this was meant to be sort of a small event.

**Comment by MXKhronos** [comment]
I updated the description to indicate it's PvP to clarify.

> I personally don't see a reason to level it other then to unlock it.

I should have stated that it's intended. It's designed to be a candy sink for people who aren't stockpilers to dump all their candies once they've unlocked all the skins this event. The reward is for people who wants to get a certain level of the badge(like those trying achieve levels of funny numbers) and is a type of intrinsic reward, as opposed to the extrinsic rewards of skins.

> antique section cooldown
As for the cooldown, the alt problem isn't going be an easy fix, it being not grindable is just so that the items maintain its scarcity. But if rerolls has to be grinded, they will still be a time lock for how much rerolls you can earn. I'll think about the ideas for next slaugherfest.

> I am putting a lot on the table here, but introducing a competative PvP event seems rather difficult compared to the usual PvE events.

Yeah, I'll keep the considerations for next slaughterfest.

**Comment by MrPigZ** [comment]
The trade offers in cauldron don't match the actual trades. Is this a bug or are the NPCs "tricking" us?
![image](https://github.com/user-attachments/assets/debdb6b9-3a94-41a2-9c80-714a4212c799)
![image](https://github.com/user-attachments/assets/87563288-9574-4241-b9ec-21a241049a1f)

**Comment by MXKhronos** [comment]
> The trade offers in cauldron don't match the actual trades. Is this a bug or are the NPCs "tricking" us?

Hmm, it's a bug but the trades are generated by a seed.. It's strange how it matched the candy types but not amount.

**Comment by Leroy8888** [comment]
I've also ran across an issue where the hints for the NPCs in the treat section didn't match with actual NPCs the player has to talk to. I haven't seen anyone mention it however.

Since I haven't heard anyone about it I presume it's something related to switching accounts and displaying an incorrect seed, because it only seems to occur if switching to another account.
![Schermopname (14890)](https://github.com/user-attachments/assets/963e3666-7722-4d66-ab01-0f2e6199f2ba)

**Comment by MXKhronos** [comment]
How old are the servers? 
I have a hunch it may have something to do with old servers.

**Comment by Leroy8888** [comment]
oh whoops, didn't see the last comment. But no, they're same server maybe a few minutes older by the time I would join with an alt. ROBLOX puts me in the same server unless I were to use a VPN to confuse it.
Left side is with my main account, right side with an alt. Both joined the same server at identical server age.
![Schermopname (15006)](https://github.com/user-attachments/assets/085ee9ea-4062-4968-b8e6-8c60e9db4dfa)
